USE [master]

RESTORE DATABASE [INFRASTRUCTURE.COMMAND] 
FROM  DISK = N'C:\SQLServer2016_BACKUP\INFRASTRUCTURE.COMMAND_BackUp_Full.bak' 
WITH  FILE = 1,  
MOVE N'INFRASTRUCTURE.COMMAND' TO N'C:\SQLServer2016_DATA\INFRA_COMMAND.MDF',  
MOVE N'INFRASTRUCTURE.COMMAND_Log' TO N'C:\SQLServer2016_DATA\INFRA_COMMAND_log.LDF',  
NOUNLOAD,  
STATS = 5

GO
